version: '3'

services:
  fraudfree:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fraud_detection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    command: ["bash", "-c", "sleep 12 && service mysql start && mysql -u root < /docker-entrypoint-initdb.d/setup.sql && apache2ctl -D FOREGROUND"]

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fraud_detection
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
